version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
      - "5000:5000"
    env_file:
      - .env
    networks:
      - appnet


  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - appnet

volumes:
  influxdb-data:

networks:
  appnet:
